[package]
name = "path_tracer"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"

[profile.release_debug]
inherits = "release"
debug = true

[dependencies.image]
version = "0.24.1"
default-features = false
features = ["jpeg", "png"]

[dependencies.mimalloc]
version = "0.1.28"
default-features = false

[dependencies.nanorand]
version = "0.7.0"
default-features = false
features = ["tls"]

[dependencies]
bumpalo = { version = "3.9.1", features = ["allocator_api"] }
enum_dispatch = "0.3.8"
glam = "0.20.2"
nohash-hasher = "0.2.0"
rayon = "1.5.1"