[package]
name = "path_tracer"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies.image]
version = "0.24.1"
default-features = false
features = ["jpeg", "png"]

[dependencies.rand]
version = "0.8.5"
features = ["getrandom"]

[dependencies.mimalloc]
version = "0.1.28"
default-features = false

[dependencies]
glam = "0.20.2"
rayon = "1.5.1"