[package]
name = "path_tracer"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"

[dependencies.image]
version = "0.24.1"
default-features = false
features = ["jpeg", "png"]

[dependencies.mimalloc]
version = "0.1.28"
default-features = false

[dependencies.nanorand]
version = "0.7.0"
default-features = false
features = ["tls"]

[dependencies]
glam = "0.20.2"
rayon = "1.5.1"